name: Tests

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lints:
    name: Lints
    env:
      RUSTFLAGS: "-D warnings"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
          - os: macos-15-intel
            arch: x86_64
          - os: macos-latest
            arch: aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          key: lint-${{ matrix.arch }}

      - name: Cargo check (lib)
        run: cargo check

      - name: Cargo check (tests)
        run: cargo check --tests

      - name: Cargo check (examples)
        run: cargo check --examples
  
  linux-tests:
    name: Linux Tests
    needs: lints
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-22.04
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
          - os: ubuntu-22.04-arm
            arch: aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: linux-${{ matrix.arch }}
      - run: cargo test --release -- --nocapture

  linux-examples:
    name: Linux Examples
    needs:
      - lints
      - linux-tests
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-22.04
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
          - os: ubuntu-22.04-arm
            arch: aarch64
        example:
          - ff
          - fm
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: examples-${{ matrix.platform.arch }}
          cache-on-failure: true

      - name: Run example
        run: cargo run --release --example ${{ matrix.example }}

  macos-tests:
    name: MacOS Tests
    needs: lints
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15-intel
            arch: x86_64
          - os: macos-14
            arch: aarch64
          - os: macos-latest
            arch: aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: macos-${{ matrix.arch }}
      - run: cargo test --release -- --nocapture

  macos-examples:
    name: MacOS Examples
    needs:
      - lints
      - macos-tests
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: macos-15-intel
            arch: x86_64
          - os: macos-14
            arch: aarch64
          - os: macos-latest
            arch: aarch64
        example:
          - ff
          - fm
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: examples-${{ matrix.platform.arch }}
          cache-on-failure: true

      - name: Run example
        run: cargo run --release --example ${{ matrix.example }}
